/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.tplp332110.view;

import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author renato
 */
public class SalvarEditarAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form SalvarEditarAluno
     */
    public SalvarEditarAluno(String titulo) {
        this.setTitle(titulo);
        initComponents();
        lblTitulo.setText(titulo);
        listTelefones.setModel(modelo);
        initialFocus();
    }

    private void initialFocus() {
        this.toFront();
        try {
            this.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(CadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        SwingUtilities.invokeLater(() -> {
            txtNome.requestFocusInWindow();
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFundo = new javax.swing.JPanel();
        pnTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnCampos = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        lbNome = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbId = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblEndereco = new javax.swing.JLabel();
        lbRua = new javax.swing.JLabel();
        lbNome1 = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtOutros = new javax.swing.JTextField();
        lbINumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        cbEstados = new javax.swing.JComboBox<>();
        lbCep = new javax.swing.JLabel();
        fmtCep = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblEndereco1 = new javax.swing.JLabel();
        lbNumero2 = new javax.swing.JLabel();
        fmtTelefone = new javax.swing.JFormattedTextField();
        lbTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        lbOutros = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTelefones = new javax.swing.JList<>();
        jSeparator4 = new javax.swing.JSeparator();
        pnBotoes = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(900, 1280));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 900));
        getContentPane().setLayout(new java.awt.FlowLayout());

        pnFundo.setMaximumSize(new java.awt.Dimension(900, 900));
        pnFundo.setMinimumSize(new java.awt.Dimension(900, 500));
        pnFundo.setPreferredSize(new java.awt.Dimension(900, 800));

        pnTitulo.setMaximumSize(new java.awt.Dimension(900, 105));
        pnTitulo.setMinimumSize(new java.awt.Dimension(900, 105));
        pnTitulo.setPreferredSize(new java.awt.Dimension(900, 105));
        pnTitulo.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Alunos");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnTitulo.add(lblTitulo, java.awt.BorderLayout.CENTER);

        pnFundo.add(pnTitulo);

        pnCampos.setMaximumSize(new java.awt.Dimension(900, 900));
        pnCampos.setMinimumSize(new java.awt.Dimension(900, 500));
        pnCampos.setPreferredSize(new java.awt.Dimension(900, 500));

        lbNome.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbNome.setText("Nome:");

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtId.setFocusable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        lbEmail.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbEmail.setText("e-mail:");

        txtNome.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNome.setMaximumSize(new java.awt.Dimension(64, 26));
        txtNome.setMinimumSize(new java.awt.Dimension(682, 26));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        lbId.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbId.setText("ID:");

        txtEmail.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtEmail.setMinimumSize(new java.awt.Dimension(682, 26));
        txtEmail.setPreferredSize(new java.awt.Dimension(682, 26));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        lblEndereco.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblEndereco.setText("Endereço");

        lbRua.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbRua.setText("Logradouro:");

        lbNome1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbNome1.setText("Cidade:");

        lbEstado.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbEstado.setText("Estado:");

        txtRua.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaActionPerformed(evt);
            }
        });
        txtRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRuaKeyPressed(evt);
            }
        });

        txtCidade.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtCidade.setMaximumSize(new java.awt.Dimension(64, 26));
        txtCidade.setMinimumSize(new java.awt.Dimension(682, 26));
        txtCidade.setPreferredSize(new java.awt.Dimension(682, 26));
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCidadeKeyPressed(evt);
            }
        });

        txtOutros.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtOutros.setMinimumSize(new java.awt.Dimension(682, 26));
        txtOutros.setNextFocusableComponent(btnExcluir);
        txtOutros.setPreferredSize(new java.awt.Dimension(682, 26));
        txtOutros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOutrosKeyPressed(evt);
            }
        });

        lbINumero.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbINumero.setText("Número:");

        txtNumero.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroKeyPressed(evt);
            }
        });

        cbEstados.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        cbEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre  ", "Alagoas  ", "Amapá  ", "Amazonas  ", "Bahia  ", "Ceará  ", "Distrito Federal  ", "Espírito Santo  ", "Goiás  ", "Maranhão  ", "Mato Grosso  ", "Mato Grosso do Sul  ", "Minas Gerais  ", "Pará  ", "Paraíba  ", "Paraná  ", "Pernambuco  ", "Piauí  ", "Rio de Janeiro  ", "Rio Grande do Norte  ", "Rio Grande do Sul  ", "Rondônia  ", "Roraima  ", "Santa Catarina  ", "São Paulo  ", "Sergipe  ", "Tocantins  " }));
        cbEstados.setSelectedIndex(11);
        cbEstados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbEstadosKeyPressed(evt);
            }
        });

        lbCep.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbCep.setText("CEP:");

        try {
            fmtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtCep.setToolTipText("Apenas números");
        fmtCep.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        fmtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fmtCepKeyPressed(evt);
            }
        });

        lblEndereco1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblEndereco1.setText("Telefone(s)");

        lbNumero2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbNumero2.setText("Número:");

        try {
            fmtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtTelefone.setToolTipText("DDD + número (Apenas número)");
        fmtTelefone.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        fmtTelefone.setNextFocusableComponent(cbTipo);
        fmtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fmtTelefoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fmtTelefoneKeyTyped(evt);
            }
        });

        lbTipo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbTipo.setText("Tipo:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha o Tipo", "Celular", "Residencial", "Comercial", "Recado", "Outros" }));
        cbTipo.setNextFocusableComponent(txtOutros);
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });
        cbTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbTipoKeyPressed(evt);
            }
        });

        lbOutros.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbOutros.setText("Outros:");

        btnAdd.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAdd.setMnemonic('x');
        btnAdd.setText(">>>");
        btnAdd.setToolTipText("Apaga os registros do aluno aluno selecionado");
        btnAdd.setEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnExcluir.setMnemonic('n');
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Incluir um novo telefone");
        btnExcluir.setEnabled(false);
        btnExcluir.setNextFocusableComponent(btnAdd);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        listTelefones.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        listTelefones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listTelefones.setToolTipText("Para Editar dê um duplo clique");
        listTelefones.setNextFocusableComponent(btnSalvar);
        listTelefones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTelefonesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listTelefones);

        txtOutros.setVisible(false);
        lbOutros.setVisible(false);

        javax.swing.GroupLayout pnCamposLayout = new javax.swing.GroupLayout(pnCampos);
        pnCampos.setLayout(pnCamposLayout);
        pnCamposLayout.setHorizontalGroup(
            pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCamposLayout.createSequentialGroup()
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCamposLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbNome)
                            .addComponent(lbEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnCamposLayout.createSequentialGroup()
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCamposLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lbNome1)
                                .addGap(3, 3, 3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCamposLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNumero2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbOutros, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbCep, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCamposLayout.createSequentialGroup()
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnCamposLayout.createSequentialGroup()
                                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fmtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnCamposLayout.createSequentialGroup()
                                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnCamposLayout.createSequentialGroup()
                                                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lblEndereco1)
                                                    .addComponent(fmtTelefone)
                                                    .addComponent(cbTipo, 0, 184, Short.MAX_VALUE)
                                                    .addComponent(txtOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnCamposLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbRua)
                        .addGap(2, 2, 2)
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEndereco)
                            .addGroup(pnCamposLayout.createSequentialGroup()
                                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lbINumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(123, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addGroup(pnCamposLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lbId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCamposLayout.createSequentialGroup()
                .addComponent(jSeparator4)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnCamposLayout.setVerticalGroup(
            pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCamposLayout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRua)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbINumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome1)
                    .addComponent(lbEstado)
                    .addComponent(cbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCep)
                    .addComponent(fmtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndereco1)
                .addGap(18, 18, 18)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnCamposLayout.createSequentialGroup()
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNumero2)
                            .addComponent(fmtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd))
                        .addGap(18, 18, 18)
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTipo)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOutros))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addGap(29, 29, 29)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pnFundo.add(pnCampos);

        pnBotoes.setMaximumSize(new java.awt.Dimension(250, 52));
        pnBotoes.setMinimumSize(new java.awt.Dimension(250, 52));
        pnBotoes.setPreferredSize(new java.awt.Dimension(250, 52));
        pnBotoes.setLayout(new java.awt.GridLayout(1, 0));

        btnSalvar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSalvar.setMnemonic('s');
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Edita os dados do aluno selecionado");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnBotoes.add(btnSalvar);

        btnCancelar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCancelar.setMnemonic('c');
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancela a operação e volta à tela anterior");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnBotoes.add(btnCancelar);

        pnFundo.add(pnBotoes);

        getContentPane().add(pnFundo);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(fmtTelefone.getText().length() == 15 &&
                cbTipo.getSelectedIndex() != 0)
            if(cbTipo.getSelectedIndex() == 5 && txtOutros.getText().length() < 3) {
                JOptionPane.showMessageDialog(pnCampos, "O campo Outros deve ser preenchido");
            }
            else {
                if(foneEditIndex != -1) {
                    if(cbTipo.getSelectedIndex() == 5)
                        modelo.setElementAt(fmtTelefone.getText() + "     " + txtOutros.getText(), foneEditIndex);
                    else
                        modelo.setElementAt(fmtTelefone.getText() + "     " + cbTipo.getSelectedItem().toString(), foneEditIndex);
                    foneEditIndex = -1;
                }                
                else if(cbTipo.getSelectedIndex() == 5 && txtOutros.getText().length() >= 3) {
                    modelo.addElement(fmtTelefone.getText() + "     " + txtOutros.getText());
                }
                else {
                    modelo.addElement(fmtTelefone.getText() + "     " + cbTipo.getSelectedItem().toString());
                }
                
                cbTipo.setSelectedIndex(0);
                txtOutros.setText("");
                lbOutros.setVisible(false);
                txtOutros.setVisible(false);
                btnAdd.setEnabled(false);
                fmtTelefone.setValue(null);
                fmtTelefone.requestFocusInWindow();
                fmtTelefone.setCaretPosition(1);
                btnExcluir.setEnabled(false);
            }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
//        setBotoes(true, false, false, false);
//        limparCampos();
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void fmtTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fmtTelefoneKeyTyped
        if (fmtTelefone.getText().length() == 15
                && cbTipo.getSelectedIndex() != 0) { // 15 caracteres ()-9 números e um espaço
            btnAdd.setEnabled(true);
            if (cbTipo.getSelectedIndex() == 5) {// 5 id de outros
                lbOutros.setVisible(true);
                txtOutros.setVisible(true);
            } else {
                lbOutros.setVisible(false);
                txtOutros.setVisible(false);
            }
        } else {
            btnAdd.setEnabled(false);
            if (cbTipo.getSelectedIndex() == 5) {// 5 índice do tipo: outros no JList
                lbOutros.setVisible(true);
                txtOutros.setVisible(true);
            } else {
                lbOutros.setVisible(false);
                txtOutros.setVisible(false);
            }
        }
    }//GEN-LAST:event_fmtTelefoneKeyTyped

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        if (fmtTelefone.getText().length() == 15
                && cbTipo.getSelectedIndex() != 0) { // 15 caracteres ()-9 números e um espaço
            btnAdd.setEnabled(true);
        } else {
            btnAdd.setEnabled(false);
        }

        if (cbTipo.getSelectedIndex() == 5) {// 5 id de outros
            lbOutros.setVisible(true);
            txtOutros.setVisible(true);
        } else {
            lbOutros.setVisible(false);
            txtOutros.setVisible(false);
        }
    }//GEN-LAST:event_cbTipoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        String options[] = {"Continuar", "Cancelar"};
        int val = JOptionPane.showOptionDialog(pnBotoes, 
                        "A exclusão será definitiva.\nConfirme a exclusão do Telefone:\n" 
                        + modelo.getElementAt(foneEditIndex),
                        "Antenção!",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.WARNING_MESSAGE, 
                        null,
                        options,
                        options[0]);
        if(val == 0) {
            modelo.remove(foneEditIndex);
            foneEditIndex = -1;
            fmtTelefone.setText("");
            cbTipo.setSelectedIndex(0);
            txtOutros.setText("");
            lbOutros.setVisible(false);
            txtOutros.setVisible(false);
            btnAdd.setEnabled(false);
            fmtTelefone.requestFocusInWindow();
            fmtTelefone.setCaretPosition(1);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void listTelefonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTelefonesMouseClicked
        if(evt.getClickCount() == 2) {
            foneEditIndex = listTelefones.getSelectedIndex();
            String campos[] = listTelefones.getSelectedValue().split("     ");
            fmtTelefone.setText(campos[0]);
            int idTipo = 5;
            for(int i = 1; i < cbTipo.getItemCount()-1; i++) {
                if(cbTipo.getItemAt(i).equalsIgnoreCase(campos[1])) {
                    idTipo = i;
                    break;
                }
            }
            
            cbTipo.setSelectedIndex(idTipo);
            if(idTipo == 5) {
                lbOutros.setVisible(true);
                txtOutros.setVisible(true);
                txtOutros.setText(campos[1]);
            }
            btnExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_listTelefonesMouseClicked

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtRua.requestFocus();
            
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtRuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRuaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNumero.requestFocus();
        }
    }//GEN-LAST:event_txtRuaKeyPressed

    private void txtNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCidade.requestFocus();
        }
    }//GEN-LAST:event_txtNumeroKeyPressed

    private void txtCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cbEstados.requestFocus();
        }
    }//GEN-LAST:event_txtCidadeKeyPressed

    private void cbEstadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbEstadosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fmtCep.requestFocus();
        }
    }//GEN-LAST:event_cbEstadosKeyPressed

    private void fmtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fmtTelefoneKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cbTipo.requestFocus();
        }
    }//GEN-LAST:event_fmtTelefoneKeyPressed

    private void fmtCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fmtCepKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fmtTelefone.requestFocus();
        }
    }//GEN-LAST:event_fmtCepKeyPressed

    private void cbTipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbTipoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(btnExcluir.isEnabled()) {
                btnExcluir.requestFocus();
            }
            else if(btnAdd.isEnabled()) {
                btnAdd.requestFocus();
            }
            else if(txtOutros.isVisible()) {
                txtOutros.requestFocus();
            }
            else {
                btnSalvar.requestFocus();
            }
        }
    }//GEN-LAST:event_cbTipoKeyPressed

    private void txtOutrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutrosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(btnExcluir.isEnabled()) {
                btnExcluir.requestFocus();
            }
            else if(btnAdd.isEnabled()) {
                btnAdd.requestFocus();
            }
            else {
                btnSalvar.requestFocus();
            }
        }
    }//GEN-LAST:event_txtOutrosKeyPressed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if(!txtNome.getText().trim().isEmpty() && !txtEmail.getText().trim().isEmpty()) {
            btnSalvar.setEnabled(true);
        }
        else {
            JOptionPane.showMessageDialog(pnCampos, "Campos Nome e e-mail devem ser preenchidos.");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    private int foneEditIndex = -1;
    private DefaultListModel<String> modelo = new DefaultListModel<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbEstados;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JFormattedTextField fmtCep;
    private javax.swing.JFormattedTextField fmtTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbINumero;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbNumero2;
    private javax.swing.JLabel lbOutros;
    private javax.swing.JLabel lbRua;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEndereco1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> listTelefones;
    private javax.swing.JPanel pnBotoes;
    private javax.swing.JPanel pnCampos;
    private javax.swing.JPanel pnFundo;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtOutros;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
